apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: smoke-test
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for app to be ready..."
              sleep 20

              echo "Running smoke tests..."

              curl -f http://capstone-app/health || exit 1
              echo "✅ Health endpoint passed"

              curl -f http://capstone-app/ || exit 1
              echo "✅ Root endpoint passed"

              curl -f http://capstone-app/users || exit 1
              echo "✅ Users endpoint passed"

              echo "✅ All smoke tests passed!"
