replicaCount: 2

image:
  repository: atulupadhyay002/eks-argocd-capstone
  pullPolicy: IfNotPresent
  tag: "c03ead3b6d3c34c0c8e16fce452e0465c1cd4d36"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
